function Mdot=odefcn_decay_constM(t,M,J)
%calculate emissions that keep atmospheric concentration constant
%Epath=\sum delta_i M_i
Mdot= ...
   [J(1)*(J(5)*M(2)+J(6)*M(3)+J(7)*M(4));  ...
    J(2)*(J(5)*M(2)+J(6)*M(3)+J(7)*M(4))-J(5)*M(2); ...
    J(3)*(J(5)*M(2)+J(6)*M(3)+J(7)*M(4))-J(6)*M(3); ...                
    J(4)*(J(5)*M(2)+J(6)*M(3)+J(7)*M(4))-J(7)*M(4)];
end